build/nupkgIncludes/Sleet.props

Since the props is imported from build\net46\Sleep.props, this should have been ..\..\tools\Sleet.exe

Fix path to Sleet.exe from props

---

src/Sleet/Sleet.csproj
src/SleetLib/SleetLib.csproj
test/Sleet.Test.Common/Sleet.Test.Common.csproj

Currently, the netcoreapp2.0 version of Sleet.dll doesn't run. It fails with
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
at Sleet.CmdUtils.LaunchDebuggerIfSet(String[]& args, ILogger logger)
at Sleet.Program.MainCore(String[] args, ILogger log)
at Sleet.Program.Main(String[] args)
```
NETStandard.Library.targets were not imported at all due to BaseIntermedateOutputPath not being set in the right order (see https://github.com/Microsoft/msbuild/issues/1603). This changes the import order so the targets are found

Fix the dependency graph when building for netcoreapp2.0

---

src/SleetLib/Services/FlatContainer.cs

With this change, Sleet will extract the `.nuspec` file from the package, even if it's not the first entry in the Zip archive.
Looks like the `.nuspec` happens to be the first entry if the package was created with NuGet, but not with Paket.

Extract the nuspec file from the package

---

ReleaseNotes.md
src/SleetLib/Commands/DeleteCommand.cs
src/SleetLib/Commands/PushCommand.cs
src/SleetLib/Commands/StatsCommand.cs
src/SleetLib/Common/JsonLDTokenComparer.cs
src/SleetLib/Common/PackageSet.cs
src/SleetLib/Common/PackageSets.cs
src/SleetLib/PackageInput.cs
src/SleetLib/Services/AutoComplete.cs
src/SleetLib/Services/Catalog.cs
src/SleetLib/Services/FlatContainer.cs
src/SleetLib/Services/PackageIndexFile.cs
src/SleetLib/Services/Registrations.cs
src/SleetLib/Services/Search.cs
src/SleetLib/Services/Symbols.cs
src/SleetLib/Services/VirtualCatalog.cs
src/SleetLib/Utility/CatalogUtility.cs
src/SleetLib/Utility/Extensions.cs
src/SleetLib/Utility/SleetUtility.cs
src/SleetLib/def/IAddRemovePackages.cs
test/Sleet.Test.Common/SleetTestContext.cs
test/SleetLib.Tests/AddRemoveTests.cs
test/SleetLib.Tests/CatalogTests.cs
test/SleetLib.Tests/FeedTests.cs
test/SleetLib.Tests/PushCommandTests.cs
test/SleetLib.Tests/SleetTestContext.cs

* Improve performance by adding multiple packages at a time to a service, this will reduce the number of file read/writes.
* Run operations in parallel within a service where possible
* Create package readers before locking the feed
Related: https://github.com/emgarten/Sleet/issues/46

Add batch APIs to improve performance

---

ReleaseNotes.md
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/LocalSettings.cs
src/SleetLib/Utility/UriUtility.cs
test/Sleet.Integration.Tests/LocalFeedTests.cs
test/SleetLib.Tests/FeedTests.cs
test/SleetLib.Tests/UriUtilityTests.cs

This allows a path relative to the sleet.json file, in a similar way to a local nuget repository can be local to a nuget.config file.
Closes #49

Add support for relative 'path' setting when using local repository type

---

src/SleetLib/FileSystem/AzureFileSystem.cs
test/Sleet.Azure.Tests/SubFeedTests.cs

It looks like the code for "paging" over a list of blobs using ListBlobsSegmentedAsync wasn't quite right. This patch changes the code to use the continuation token returned with each request, rather than holding on to the original (null) value in perpetuity.
This one with clean history.

Fixes potential infinite loop while listing Blobs (revised)

---

src/SleetLib/Commands/CreateConfigCommand.cs
src/SleetLib/FileSystem/FileSystemFactory.cs

This change removes the `accessKeyId` and `secretAccessKey` elements created by `CreateConfigCommand` and add a new `profileName` key.  It also changes the `AmazonS3Client` constructor used in `FileSystemFactory` to make use of the provided profile if keys aren't provided. This is not a breaking change since keys provided in existing `sleet.json` files will be preferred.

Encourage AWS profile name rather than keys in sleet.config

---

src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/Utility/UriUtility.cs

- In UriUtility.cs the check `path.Length == 0`  made at line 77 throws when true.  The subsequent check `path.Length < 1` is then superfluous since we know it isn't.
- In FileSystemFactory.cs the check `sources == null` at line 25 likewise throws when found to be true, making the subsequent check for `sources != null` always true and uneeded.

Removes two constant conditional expressions.

---

src/SleetLib/Commands/CreateConfigCommand.cs

Currently, the command `sleet createconfig` produces output like:
```
{
"username": "",
"useremail": "",
"sources": []
}
```
Which leave the user guessing a bit about what goes in `sources`. It's minor, but helpful to suggest the bare minium starting point for a source:
```
{
"username": "",
"useremail": "",
"sources": [
{
"name": "myFeed",
"type": ""
}
]
}
```

Create a little json for unspecified feed types.

---

Sleet.sln
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/LocalSettings.cs
src/SleetLib/Utility/SettingsUtility.cs
test/Sleet.Integration.Tests/LocalFeedTests.cs
test/SleetLib.Tests/FeedTests.cs

- Corrects misnamed `sleet.json` in tests and error messages
- Makes relative paths work when `sleet.json` is unspecified or specified as file in current directory
Fixes #59

Relative local fixes 59

---

ReleaseNotes.md
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/FileBase.cs
src/SleetLib/FileSystem/ISleetFile.cs
src/SleetLib/Services/FlatContainer.cs
src/SleetLib/Services/VirtualCatalog.cs
src/SleetLib/Utility/CatalogUtility.cs
src/SleetLib/Utility/Extensions.cs
test/SleetLib.Tests/AddRemoveTests.cs
test/SleetLib.Tests/PhysicalFileSystemTests.cs

* Skip package SHA512 hashing when the catalog is disabled. Package details blobs will no longer write this extra property.
* ISleetFile.Link support
* Nupkgs are no longer copied to the temp cache during push. This improves perf and saves disk space for large pushes.

Reduce nupkg operations

---

src/SleetLib/FileSystem/FileSystemFactory.cs

Fixes #63 
This replaces the earlier attempt (#67) which only seemed to work occasionally. This is now using `CredentialCache.DefaultNetworkCredentials` which [is documented](https://docs.microsoft.com/en-us/dotnet/api/system.net.credentialcache.defaultnetworkcredentials?view=netcore-2.1) as the standard way to get the credentials of the current user. 
I have done more reading and experimenting and digging into the S3 SDK code and one thing to note is that the current proxy behaviour in the SDK is different between .net core and .net framework. I have verified that the solution works for .net core but could not get it to help with .net framework since the SDK doesn't look up the proxy settings for .net framework. It may be that they expect people to set it using app.config instead in …

Set proxy credentials using standard 'DefaultNetworkCredentials'

---

src/SleetLib/Commands/DeleteCommand.cs
src/SleetLib/Commands/DestroyCommand.cs
src/SleetLib/Commands/DownloadCommand.cs
src/SleetLib/Commands/FeedSettingsCommand.cs
src/SleetLib/Commands/PushCommand.cs
src/SleetLib/Commands/RecreateCommand.cs
src/SleetLib/Commands/StatsCommand.cs
src/SleetLib/Commands/ValidateCommand.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/AzureFileSystemLock.cs
src/SleetLib/FileSystem/FileSystemLockBase.cs
src/SleetLib/FileSystem/ISleetFileSystemLock.cs
src/SleetLib/FileSystem/PhysicalFileSystemLock.cs
src/SleetLib/LocalSettings.cs
src/SleetLib/Utility/SourceUtility.cs
test/SleetLib.Tests/FileSystemLockTests.cs

Store details on the action being performed and when the lock was first obtained. Clients waiting for the lock can read this info to provide a helpful message to users waiting.

Add lock message

---

src/SleetLib/FileSystem/FileBase.cs
src/SleetLib/FileSystem/FileSystemBase.cs
src/SleetLib/FileSystem/ISleetFile.cs
src/SleetLib/FileSystem/ISleetFileSystem.cs
src/SleetLib/Utility/SourceUtility.cs
test/Sleet.Integration.Tests/NuGetReaderTests.cs
test/SleetLib.Tests/AddRemoveTests.cs
test/SleetLib.Tests/FeedTests.cs
test/SleetLib.Tests/FileSystemTests.cs
test/SleetLib.Tests/PushCommandTests.cs
test/SleetLib.Tests/SymbolsTests.cs

File systems track ISleetFiles in memory which point to files in the local cache. If the same file system is reused between commands/locks it can become out of date and will end up using older versions of files. To avoid this the file system should be reset after each lock. Files taken from before the reset should be invalidated and should fail when used to avoid problems.
//cc @jcagme  this should help avoid problems like the ones you hit for delete and earlier with reading the package index before the lock and then pushing.

Add file system reset and cache invalidation

---

ReleaseNotes.md
src/SleetLib/AssemblyVersionHelper.cs
src/SleetLib/Commands/DownloadCommand.cs
src/SleetLib/Commands/FeedSettingsCommand.cs
src/SleetLib/Commands/RecreateCommand.cs
src/SleetLib/Commands/StatsCommand.cs
src/SleetLib/Models/FeedCapability.cs
src/SleetLib/Models/FeedRequirements.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/SourceUtility.cs
src/SleetLib/Utility/UpgradeUtility.cs
test/SleetLib.Tests/UpgradeUtilityTests.cs

This change removes the previous logic that compared the assembly version
to sleet:version in index.json. Capabilities support fine grained control
over compatibility based on what features in the feed are actually used.
Support for sleet:requiredVersion has also been added to limit the feed to
certain sleet client versions if needed.
After this change Sleet will be able to version itself in a helpful way for
users without breaking compatibility with older feeds that will still work fine.

Add capabilities to determine client/feed compat

---

ReleaseNotes.md
src/SleetLib/Commands/InitCommand.cs
src/SleetLib/Commands/PushCommand.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/FileSystemBase.cs
src/SleetLib/FileSystem/ISleetFileSystem.cs
src/SleetLib/FileSystem/PhysicalFileSystem.cs
src/SleetLib/Utility/SourceUtility.cs
test/Sleet.AmazonS3.Tests/AmazonS3FileSystemTests.cs
test/Sleet.AmazonS3.Tests/AmazonS3NuGetIntegrationTests.cs
test/Sleet.AmazonS3.Tests/AmazonS3TestContext.cs
test/Sleet.AmazonS3.Tests/BasicTests.cs
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.Azure.Tests/AzureFileSystemTests.cs
test/Sleet.Azure.Tests/AzureNuGetIntegrationTests.cs
test/Sleet.Azure.Tests/AzureTestContext.cs
test/Sleet.Azure.Tests/BasicTests.cs
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/SleetLib.Tests/PhysicalFileSystemTests.cs
test/SleetLib.Tests/PushCommandTests.cs

* Automatically create folders/containers/buckets for new feeds if they do not exist.
* Automatically initialize new feeds if they have not yet been initialized.
* Feeds will be public by default.
This change makes it easier to create feeds as part of build scripts.
Note that this is a breaking change, so it will be part of 3.0.0.

Auto initialize new feeds

---

src/Sleet/CreateConfigAppCommand.cs
src/SleetLib/Commands/CreateConfigCommand.cs
src/SleetLib/FileSystem/FileSystemStorageType.cs

I'm try to run without a config file, passing everything in through the command line.  If I pass in `-p SLEET_FEED_TYPE=S3` the value "s3" doesn't match the enum `FileSystemStorageType.AmazonS3` and so `GetConfigFromEnv` fails to parse the env vars. If I pass in `-p SLEET_FEED_TYPE=AmazonS3`
`CreateFileSystemAsync` returns null because of the line 115 `else if (type == "s3")`

Fix bug preventing specifying S3 type on the command line and env vars.

---

src/SleetLib/SleetLib.csproj

At the moment the version of the AWS security token package is 10 months out of date and I think that is why my attempt to use [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) isn't working.
It also seems like it was an oversight to use the variable for the S3 package but not this package.

Use AWSSDKVersion variable for security token package

---

src/SleetLib/FileSystem/AmazonS3FileSystem.cs

The deprecated method always uses HTTP rather than HTTPS which wasn't working with our proxy setup, or possibly our S3 bucket policy.

Use non-deprecated method for checking S3 bucket existence

---

ReleaseNotes.md
doc/client-settings.md
src/Sleet/Util.cs
src/SleetLib/Utility/SettingsUtility.cs
test/Sleet.AmazonS3.Tests/BasicTests.cs

Add support for the proxy useDefaultCredentials sleet.json setting.
This gives the equivalent of WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultCredentials
Fixes https://github.com/emgarten/Sleet/issues/119

DefaultWebProxy support for authenticated proxies

---

build/common/common.ps1
doc/client-settings.md
doc/feed-type-azure.md
doc/feed-type-local.md
doc/feed-type-s3.md
src/SleetLib/LocalSettings.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/SettingsUtility.cs
test/Sleet.CmdExe.Tests/DynamicSettingsTests.cs
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/SleetLib.Tests/ConfigTests.cs

The [dotnetconfig](https://dotnetconfig.org) format allows hierarchical
tool settings to be persisted and read in a standards way by multiple
tools simultaneously. By adding this support to the tool, all settings
can now also be persisted to the`.netconfig` in the current directory
to streamline subsequent runs. In addition, for scenarios where multiple
projects/repositories in the local machine produce packages that are
pushed to the same feed(s), the `.netconfig` support makes it trivial
to reuse those settings across the entire machine by saving the settings
to the user profile instead.
Updated the docs to cover both `sleet.json` and `.netconfig` formats
equally.

Add support for configuring with .netconfig

---

ReleaseNotes.md
doc/commands.md
src/Sleet/RetentionPruneAppCommand.cs
src/Sleet/RetentionSettingsAppCommand.cs
src/SleetLib/Commands/RetentionPruneCommand.cs
src/SleetLib/Commands/RetentionPruneCommandContext.cs
src/SleetLib/Commands/RetentionSettingsCommand.cs
src/SleetLib/SourceSettings.cs
src/SleetLib/Utility/FeedSettingsUtility.cs
src/SleetLib/Utility/RetentionUtility.cs
test/SleetLib.Tests/FeedSettingsUtilityTests.cs
test/SleetLib.Tests/RetentionPruneCommandTests.cs
test/SleetLib.Tests/RetentionSettingsCommandTests.cs
test/SleetLib.Tests/RetentionUtilityTests.cs

* Add feed setting for package retention with release labels
* Add prune option for release labels
* Group packages by their first X release labels when applying pruning
Fixes https://github.com/emgarten/Sleet/issues/129

Package retention support for release labels

---

doc/external-search.md
doc/index.md
src/SleetLib/Commands/FeedSettingsCommand.cs
src/SleetLib/Commands/RecreateCommand.cs
src/SleetLib/ExternalSearchHandler.cs
src/SleetLib/SourceSettings.cs
src/SleetLib/Utility/FeedSettingsUtility.cs
src/SleetLib/def/IFeedSettingHandler.cs
test/SleetLib.Tests/ExternalSearchTests.cs

* Add `externalsearch` feed setting
* Add `IFeedSettingHandler` to support additional feed changes when a setting is updated
* `ExternalSearchHandler` will update the search URI in `index.json` when `externalsearch` is set or unset
Fixes https://github.com/emgarten/Sleet/issues/79

Support external search URIs

---

.travis.yml
ReleaseNotes.md
appveyor.yml
build.ps1
build/build.proj
build/common/common.ps1
build/common/common.sh
src/Sleet/Sleet.csproj
src/SleetLib/SleetLib.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/Sleet.Test.Common/Sleet.Test.Common.csproj
test/SleetLib.Tests/SleetLib.Tests.csproj

* Update dotnet format
* Publish Sleet.exe as a standalone file instead of using ILMerge
* Remove net472 support in favor of netstandard2.0

Sleet exe standalone publish

---

build/common/common.ps1
build/config.props
src/SleetLib/SleetLib.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Test.Common/Sleet.Test.Common.csproj

dotnet format fails on the CI over project metadata issues. It isn't clear what is causing this and the formatter does not need to run on the CI so it will now be skipped in CI scenarios.

Fix formatter errors

---

src/SleetLib/FileSystem/FileSystemFactory.cs
test/Sleet.AmazonS3.Tests/AmazonS3TestContext.cs

I found this in the AWS S3 document https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html: 
> The AWS SDK for .NET enables you to configure the request timeout and socket read/write timeout values at the service client level. These values are specified in the Timeout and the ReadWriteTimeout properties of the abstract [Amazon.Runtime.ClientConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html) class. These values are passed on as the Timeout and ReadWriteTimeout properties of the [HttpWebRequest](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest) objects created by the AWS service client object. By default, the Timeout value is 100 seconds and the ReadWriteTimeout value is 300 seconds...
The versions of the …

Set a timeout value for the AmazonS3Client

---

README.md
ReleaseNotes.md
build/config.props
doc/feed-type-s3.md
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/AmazonS3Utility.cs

Add support for AWS profiles with SSO 
I based this work on: 
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/sso.html
It looks relatively straight forward to add, however it is unclear how this works as a fallback with the existing profile support and unfortunately I don't have an SSO account to test this with.
As a fallback this should be safe since the existing profile load runs first. My concern is when looking at the code for the existing profile load I see internally it runs with `isSsoSession: false` and doesn't appear to allow setting it to true.
Potentially an SSO profile could get loaded from the existing profile load. The result may or may not work due to that flag. If it gives incomplete credentials it may return true and not fallback to the new SSO code.
I'm going …

Add AWS SSO support

---

ReleaseNotes.md
doc/index.md
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
test/Sleet.AmazonS3.Tests/SubFeedTests.cs

* Updated AmazonS3FileSystem.GetFiles to account for sub paths when retrieving all files in the feed
* This call is currently only used by Destroy, other scenarios should not be impacted
* Previous behavior was resulting in the sub path being duplicated in the URI, which resulted in files not being found.
* Updated the S3 sub path functional test to verify the feed is fully removed.
Fixes https://github.com/emgarten/Sleet/issues/185

Fix S3 destroy for feeds with sub paths

---

build/config.props
doc/ci-server.md
src/SleetLib/FileSystem/AzureBlobLease.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/AzureFileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/AzureUtility.cs
test/Sleet.Azure.Tests/AzureFileSystemTests.cs
test/Sleet.Azure.Tests/AzureNuGetIntegrationTests.cs
test/Sleet.Azure.Tests/AzureTestContext.cs
test/Sleet.Azure.Tests/BasicTests.cs
test/Sleet.Azure.Tests/SubFeedTests.cs

Replace `Microsoft.Azure.Storage.Blob` with `Azure.Storage.Blobs` package.
Upgrading is a good idea because
1. `Microsoft.Azure.Storage.Blob` is no longer supported
2. `Azure.Storage.Blobs` will get bug fixes/new features
3. `Azure.Storage.Blobs` supports modern auth (service principals, managed identities)

Replace `Microsoft.Azure.Storage.Blob` with `Azure.Storage.Blobs` package

---

ReleaseNotes.md
doc/feed-type-azure.md
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/Utility/AzureUtility.cs
test/Sleet.Azure.Tests/AzureFileSystemTests.cs
test/Sleet.Azure.Tests/AzureTestContext.cs

* For Azure connection string scenarios auto populate `path` to the full container URI instead of the storage account URI
* Added a FileSystemFactory test for Azure to ensure this is covered, previous tests were creating an AzureFileSystem directly
* Update azure specific doc to include details on using service principals like the client settings doc.
Fixes https://github.com/emgarten/Sleet/issues/197

Use the full container uri when path is not set

---

ReleaseNotes.md
build/config.props
src/SleetLib/FileSystem/FileSystemFactory.cs

* Updated AWS SDK packages to improve support for non AWS S3 storage
* Updated Azure Storage and Azure Identity packages to fix vulnerability
* ECSTaskCredentials -> GenericContainerCredentials
* ECSTaskCredentials is now deprecated
* Copied the env var name directly into the code since it is now internal in GenericContainerCredentials

Update AWS and Azure packages

---

doc/client-settings.md
doc/feed-type-s3.md
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs

Some S3 compatible storage such as R2 do not support the Streaming SigV4 implementation used by AWSSDK.S3 which can be bypassed by setting DisablePayloadSigning = true when pushing to S3

add disablePayloadSigning option

---

ReleaseNotes.md
build.sh
build/config.props
src/SleetLib/Commands/InitCommand.cs
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/Services/FlatContainer.cs
test/Sleet.AmazonS3.Tests/BasicTests.cs
test/Sleet.Azure.Tests/BasicTests.cs
test/SleetLib.Tests/AddRemoveTests.cs
test/SleetLib.Tests/InitCommandTests.cs

* Update NuGet.Test.Helpers to get support for readme files in test packages
* README files (if they exist) will now be copied to the flatcontainer folder for that package version along side the icon, nuspec, and nupkg
* readme files have a content type of `text/markdown` 
* Files are NOT compressed, this doesn't work with Visual Studio in my testing
* This feature is always on, there isn't a good reason to disable this or make it optional
* The service index json file will now have an entry added for the template to build the README url
* Existing feeds will need to do a `recreate` to update the index or may have to edit it manually to get Visual Studio to pick it up
Fixes https://github.com/emgarten/Sleet/issues/212

Add README support

---

src/Sleet/Util.cs
src/SleetLib/FileSystem/AzureFileSystem.cs

- ensure Azure file system validates container path correctly
- guard against null proxy when setting credentials

Fix path validation and proxy init

---

src/SleetLib/FileSystem/AmazonS3File.cs

fix json parsing error on upload
