README.md

Added quickstart guide for local feed, updated quickstart guide formatting

---

src/SleetLib/Utility/CatalogUtility.cs
test/SleetLib.Tests/CatalogTests.cs

Once this is in and published as a package I have another PR for `NuGet.CatalogReader` (a small optimization).
Dope project by the way 🥇!

Fix bug preventing multiple catalog pages

---

src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/FileSystemBase.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/FileSystem/PhysicalFileSystem.cs

Adding the concept of relativePath in case the feed we want to work on is different from the container

Adding support for nested feeds

---

src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/FileBase.cs
src/SleetLib/Services/Catalog.cs
src/SleetLib/Services/Registrations.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/CatalogUtility.cs
src/SleetLib/Utility/JsonUtility.cs
test/SleetLib.Tests/BaseUriTests.cs
test/SleetLib.Tests/FeedTests.cs
test/SleetLib.Tests/TestUtility.cs

We have a strong dependency in Json.NET version 9.0.1 and currently Sleet uses 10.0.1 so adding conditionals to make the switch depending on the framework

Using 9.0.1 in netcoreapp1.3 and net4.5

---

src/SleetLib/Commands/CreateConfigCommand.cs
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/FileSystemFactory.cs

PR for
https://github.com/emgarten/Sleet/issues/20

Improved Exception Message for not yet configured Azure accounts

---

build.sh
build/common/common.ps1
build/common/common.sh
build/common/common.shared.props
build/common/common.targets
build/common/packages.common.config
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.CliTool.Tests/Sleet.CliTool.Tests.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/SleetLib.Tests/SleetLib.Tests.csproj

* Update to cli 2.0.3
* Move build.sh logic to build/common
* Update test SDK
* Update Xunit runner

Update cli to 2.0.3

---

README.md
Sleet.sln
build/build.proj
src/Sleet/CreateConfigAppCommand.cs
src/SleetLib/Commands/CreateConfigCommand.cs
src/SleetLib/Common/TaskUtils.cs
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/FileSystem/FileSystemStorageType.cs
src/SleetLib/SleetLib.csproj
test/Sleet.AmazonS3.Tests/AmazonS3TestContext.cs
test/Sleet.AmazonS3.Tests/BasicTests.cs
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.AmazonS3.Tests/SubFeedTests.cs

Implement file-system interfaces using  Amazon S3 storage.

Support Amazon S3 storage

---

README.md
ReleaseNotes.md
doc/client-settings.md
doc/commands.md
doc/index.md
src/Sleet/Constants.cs
src/Sleet/CreateConfigAppCommand.cs
src/Sleet/DeleteAppCommand.cs
src/Sleet/DestroyAppCommand.cs
src/Sleet/DownloadAppCommand.cs
src/Sleet/FeedSettingsAppCommand.cs
src/Sleet/InitAppCommand.cs
src/Sleet/PushAppCommand.cs
src/Sleet/RecreateAppCommand.cs
src/Sleet/StatsAppCommand.cs
src/Sleet/ValidateAppCommand.cs
src/SleetLib/Commands/RecreateCommand.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/LocalSettings.cs
src/SleetLib/Utility/JsonUtility.cs
src/SleetLib/Utility/SettingsUtility.cs
src/SleetLib/Utility/SourceUtility.cs
test/Sleet.CmdExe.Tests/DynamicSettingsTests.cs
test/SleetLib.Tests/RecreateCommandTests.cs
test/SleetLib.Tests/SettingsUtilityTests.cs

Add support for tokenized sleet.json files
* .pp file transform support for sleet.json
* load feeds from SLEET_FEED_ env vars
* pass env var properties using --property on the command line
fixes https://github.com/emgarten/Sleet/issues/39

Improve usablity for CI scenarios

---

README.md
doc/client-settings.md
doc/feed-type-azure.md
doc/feed-type-local.md
doc/feed-type-s3.md
doc/index.md
src/SleetLib/Commands/CreateConfigCommand.cs
src/SleetLib/FileSystem/FileSystemFactory.cs

* Add additional error messages for AWS S3 feeds
* Add informational message when creating a new s3 config to list alternative ways to provide keys
* Add new settings to s3 docs
* Clean up README

AWS settings error messages

---

ReleaseNotes.md
doc/commands.md
src/Sleet/DownloadAppCommand.cs
src/SleetLib/Commands/DownloadCommand.cs

* Added Download command options: --no-lock --skip-existing --ignore-errors
* Refactored download command to use TaskUtils for threading
* Added perf summary for download

Add DownloadCommand switches

---

src/SleetLib/FileSystem/FileSystemFactory.cs

I did a quick trial on a non-proxied machine and it seemed to still work fine
Fixes #63

Add proxy support for S3 sources

---

README.md
doc/index.md
doc/symbol-server.md

Add documentation for setting up the sleet symbol server 
Fixes https://github.com/emgarten/Sleet/issues/30

Add symbol store doc

---

doc/feed-type-local.md

fileExtensions > fileExtension
Lost a good half hour on this one 💩

Typo in web.config

---

src/SleetLib/Commands/DeleteCommand.cs
test/SleetLib.Tests/AddRemoveTests.cs

Add DeleteCommand.DeletePackagesAsync for batch delete operations
//cc @jcagme

Add batch delete helper

---

build/build.proj
build/common/common.ps1
build/common/common.sh
build/config.props
src/Sleet/Sleet.csproj
src/SleetLib/FileSystem/AzureBlobLease.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/AzureFileSystem.cs
src/SleetLib/FileSystem/AzureFileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/AzureUtility.cs
src/SleetLib/Utility/CatalogUtility.cs
test/Sleet.Azure.Tests/AzureTestContext.cs
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.Azure.Tests/SubFeedTests.cs
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/NuGetReaderTests.cs
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/Sleet.Test.Common/Sleet.Test.Common.csproj
test/SleetLib.Tests/SleetLib.Tests.csproj

[x] Remove netstandard 1.0 support
[x] Migrate to new azure storage package
[x] Update packages

Misc updates to target frameworks and packages

---

build/config.props
doc/feed-type-s3.md
src/Sleet/Sleet.csproj
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/AmazonS3Utility.cs

Stop throwing so it will use IAM credentials

Support AWS IAM Role Credentials

---

build/config.props
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/AmazonS3Utility.cs

@medianotion can you give this a go?  This still works for the simple EC2 case I use.

Use GetCallerIdentityAsync

---

src/Sleet/Common/ExceptionUtils.cs
src/Sleet/Util.cs
src/SleetLib/FileSystem/FileSystemFactory.cs

* Include AWS GetCallerIdentityAsync exception in argument exception
* Fix for `SLEET_DEBUG="1"` to enable debug output properly
* Include all inner exceptions at debug level output

Include AWS GetCallerIdentityAsync exception in argument exception

---

ReleaseNotes.md
build.ps1
build/common/common.ps1
build/common/common.sh
src/Sleet/Sleet.csproj
src/Sleet/StatsAppCommand.cs
src/SleetLib/Commands/PushCommand.cs
src/SleetLib/Common/JsonLDTokenComparer.cs
src/SleetLib/Common/PackageSet.cs
src/SleetLib/FileSystem/ISleetFileSystem.cs
src/SleetLib/Utility/SettingsUtility.cs
src/SleetLib/Utility/UriUtility.cs
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.CliTool.Tests/Sleet.CliTool.Tests.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/SleetLib.Tests/CatalogTests.cs
test/SleetLib.Tests/FeedSettingsCommandTests.cs
test/SleetLib.Tests/FeedTests.cs
test/SleetLib.Tests/SettingsUtilityTests.cs
test/SleetLib.Tests/SleetLib.Tests.csproj

* Sleet will now target netcorepp2.1 and netcoreapp3.0 for dotnet tool support
* Move test projects to netcoreapp3.0
* Add dotnet format to build script
* Checked in fixes from dotnet-format

netcoreapp3.0 support

---

ReleaseNotes.md
src/SleetLib/Common/ExceptionUtilsSleetLib.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/AzureFileSystemLock.cs
src/SleetLib/FileSystem/PhysicalFileSystemLock.cs

* Log exceptions as warnings when unable to obtain a lock on feeds
Fixes https://github.com/emgarten/Sleet/issues/76
Fixes https://github.com/emgarten/Sleet/issues/97

Improve logging for feed lock failures

---

doc/client-settings.md
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
test/Sleet.AmazonS3.Tests/BasicTests.cs
test/Sleet.AmazonS3.Tests/SubFeedTests.cs

Add optional setting for S3 object encryption and fix s3 docs

---

README.md
doc/ci-server.md
doc/index.md

Add documents about Github Action

---

ReleaseNotes.md
build/config.props
doc/badges.md
doc/index.md
src/SleetLib/Commands/PushCommand.cs
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/Logging/SleetPerfGroup.cs
src/SleetLib/Services/Badges.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/SourceSettings.cs
src/SleetLib/TemplateUtility.cs
src/SleetLib/Utility/BadgeUtility.cs
src/SleetLib/Utility/FeedSettingsUtility.cs
src/SleetLib/Utility/SleetUtility.cs
src/SleetLib/Utility/Utility.cs
src/SleetLib/compiler/resources/badge.xml
test/SleetLib.Tests/BadgeFileTests.cs
test/SleetLib.Tests/BadgeUtilityTests.cs
test/SleetLib.Tests/FeedSettingsUtilityTests.cs

Add support for generating stable and prerelease SVG version badges 
https://github.com/emgarten/Sleet/issues/111

SVG version badges

---

src/SleetLib/Utility/BadgeUtility.cs

Generates a json file compatible with [shields.io /endpoint](https://shields.io/endpoint)
Note, shields.io /endpoint currently does not correctly handle gzipped json files (https://github.com/badges/shields/issues/5868). There is already a [PR open](https://github.com/badges/shields/pull/5869) in the shields.io repo with a fix

generate shields.io json file

---

ReleaseNotes.md
doc/badges.md
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AzureFile.cs
src/SleetLib/FileSystem/FileBase.cs
src/SleetLib/Services/ServiceNames.cs
src/SleetLib/Utility/PathUtility.cs
src/SleetLib/Utility/SleetUtility.cs
test/Sleet.Test.Common/CmdRunner.cs
test/SleetLib.Tests/BadgeFileTests.cs
test/SleetLib.Tests/SleetUtilityTests.cs

Remove compression for badges
* Add a helper to find which service a file is under
* Skip compression for all badges files, both svg and json
* Add tests for badges
Fixes https://github.com/emgarten/Sleet/issues/131
Fixes https://github.com/emgarten/Sleet/issues/132

Remove compression for badges

---

ReleaseNotes.md
build/common/common.ps1
build/common/common.sh
build/common/common.targets
src/Sleet/ConsoleLogger.cs
src/Sleet/Sleet.csproj
src/SleetLib/CatalogIndexEntry.cs
src/SleetLib/Common/HashCodeCombiner.cs
src/SleetLib/SleetOperation.cs
src/SleetLib/Utility/SymbolsIndexUtility.cs
src/SleetLib/Utility/SymbolsUtility.cs
src/SleetLib/def/IPackagesLookup.cs
src/SleetLib/def/IRootIndex.cs
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.AmazonS3.Tests/SubFeedTests.cs
test/Sleet.Azure.Tests/BasicTests.cs
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.CliTool.Tests/BasicTests.cs
test/Sleet.CliTool.Tests/Sleet.CliTool.Tests.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/Sleet.Integration.Tests/TestHttpSource.cs
test/SleetLib.Tests/DestroyTests.cs
test/SleetLib.Tests/FeedSettingsUtilityTests.cs
test/SleetLib.Tests/SleetLib.Tests.csproj
test/SleetLib.Tests/SleetUtilityTests.cs

* Update to net5.0
* Drop netcoreapp2.1 and netcoreapp3.1 support from Sleet dotnet tool package
* netstandard and net472 support will remain the same
* Update test SDK
* Update dotnet cli install scripts

Migrate to net5.0

---

build/config.props

Update NuGet.Packaging library, Newtonsoft.Json, and other dependencies.

Update package dependencies

---

ReleaseNotes.md
build/common/common.shared.props
build/common/common.targets
build/config.props
src/Sleet/Sleet.csproj
src/Sleet/SleetExe.nuspec
src/SleetLib/PackageInput.cs
src/SleetLib/Services/Catalog.cs
src/SleetLib/Services/FlatContainer.cs
src/SleetLib/Services/Symbols.cs
src/SleetLib/Services/VirtualCatalog.cs
src/SleetLib/Utility/CatalogUtility.cs
test/Sleet.Integration.Tests/NuGetReaderTests.cs
test/SleetLib.Tests/AddRemoveTests.cs
test/SleetLib.Tests/CatalogTests.cs

* Add icon to flatcontainer
* Remove support for legacy iconUrl
* Update misc Sleet build files
Fixes https://github.com/emgarten/Sleet/issues/107

Package icon suppport

---

ReleaseNotes.md
build.ps1
build/common/common.ps1
build/common/common.sh
build/common/common.targets
build/config.props
build/packages.config
src/Sleet/Sleet.csproj
src/SleetLib/FileSystem/AmazonS3File.cs
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
src/SleetLib/FileSystem/AmazonS3FileSystemAbstraction.cs
src/SleetLib/FileSystem/AmazonS3FileSystemLock.cs
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
src/SleetLib/Utility/JsonUtility.cs
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.CliTool.Tests/BasicTests.cs
test/Sleet.CliTool.Tests/Sleet.CliTool.Tests.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/SleetLib.Tests/SleetLib.Tests.csproj

* Add dotnet 6.0 for LTS support
* Remove dotnet 5.0 support
* Remove SLEETLEGACY and other legacy compiler flags
* Update dependency packages

Move from dotnet 5.0 to dotnet 6.0

---

ReleaseNotes.md
build/config.props
build/packages.config
src/SleetLib/FileSystem/AmazonS3FileSystem.cs

* Update NuGet.* to 6.2.1
* Remove Newtonsoft.Json 6.0.8 reference that is unused

Update NuGet.* packages and remove Newtonsoft.Json 6.0.8 reference

---

ReleaseNotes.md
build/common/common.ps1
build/common/common.sh
build/common/common.targets
build/config.props
src/Sleet/Sleet.csproj
src/SleetLib/FileSystem/AmazonS3FileSystem.cs
test/Sleet.AmazonS3.Tests/AmazonS3TestContext.cs
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj

* Add support for net7.0 in Sleet dotnet tool package
* Upgrade dependencies for AWS

Add net7.0 support to dotnet tool package

---

src/SleetLib/FileSystem/FileSystemFactory.cs

Rather than repeating the same code twice to create the AmazonS3Config object I made change in couple of lines

Made a small change 

---

ReleaseNotes.md
build/common/common.ps1
build/common/common.sh
build/common/common.shared.props
build/common/common.targets
build/config.props
src/Sleet/Sleet.csproj
src/SleetLib/FileSystem/FileSystemFactory.cs
src/SleetLib/SleetLib.csproj
test/Sleet.AmazonS3.Tests/Sleet.AmazonS3.Tests.csproj
test/Sleet.Azure.Tests/Sleet.Azure.Tests.csproj
test/Sleet.CliTool.Tests/Sleet.CliTool.Tests.csproj
test/Sleet.CmdExe.Tests/Sleet.CmdExe.Tests.csproj
test/Sleet.Integration.Tests/Sleet.Integration.Tests.csproj
test/SleetLib.Tests/SleetLib.Tests.csproj

* Add net8.0 support
* Remove net7.0 support
* Update NuGet.* packages to 6.8.0

.NET 8.0 support

---

ReleaseNotes.md
build/config.props

* Update all AWS packages
Fixes https://github.com/emgarten/Sleet/issues/182

Update all AWS packages

---

ReleaseNotes.md
build/common/common.ps1
build/config.props

Fixes https://github.com/emgarten/Sleet/issues/189

Update NuGet packages to 6.9.1 to address CVE

---

.github/workflows/dotnet.yml
.github/workflows/functional.yml
build.ps1
build/common/common.ps1
build/common/common.sh

* Remove dotnet format
* It is injecting new code and giving strange behavior when the new azure storage library is added
* Revert an earlier change to the github action for running manually

Remove dotnet format

---

test/SleetLib.Tests/ExternalSearchTests.cs

Add test for external feeds when pushing

Add test for external feeds when pushing
